title: Your Name
description: "Short tagline or role"
url: "https://yourusername.github.io"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Theme basics
minimal_mistakes_skin: default
markdown: kramdown

author:
  name: "Your Name"
  avatar: "/assets/img/avatar.jpg"   # optional; replace or remove
  bio: "One-line bio here."
  location: "City, Country"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:you@example.com"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/yourusername"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/yourprofile"