title: Shayan Dodge
description: "Short tagline or role"
url: "https://shayandodge.github.io"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Theme basics
minimal_mistakes_skin: default
markdown: kramdown

author:
  name: "Shayan Dodge"
  avatar: "/assets/img/avatar.jpg"   # optional; replace or remove
  bio: "PhD @ University of Pisa"
  location: "Pisa, Italy"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:you@example.com"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/shayandodge"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/yourprofile"
